global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'java-application'
    static_configs:
      - targets: ['34.143.169.241:8080']  # Ensure this matches your application's IP and port
